### ISSUE TITLE
`priority: medium` usage ?

### ISSUE THREAD

**Issue by lauriejim** [abdonrd/github-labels#1]
Hi @abdonrd !

I actually have a question about `priority: medium` label.

`priority: low` mean we will not work on it soon and maybe never, generally used with `status: wont do/fix`.
`priority: hight` and `priority: critical` have sense.

But have we to apply `priority: medium` to all others issue or just delete this priority to not pollute issue labels ?

> Apply label it's good for search, but it's the only usage I see.

**Comment by abdonrd** [comment]
I like the idea that all issues have a priority assigned.

When I look the sidebar, at a glance I see how the issue is:
<img width="235" alt="github-labels-asign" src="https://user-images.githubusercontent.com/1007051/39631668-15717ef4-4fb3-11e8-836a-8cbc8f99d2cb.png">

It would be great if GitHub allowed us to assign labels by default. 😕
We could add `priority: medium` automatically.

---

Friendly ping to @juan-cb, @ydarias & @jesusprubio.

**Comment by lauriejim** [comment]
Do you have other projects which use these labels ? (with type, status and priority)

**Comment by cbjuan** [comment]
Hi @lauriejim 

We have discussed this kind of labels internally at our team, and the result is a mix of our previous experience (also gained by working with other tracking/ticketing systems) and the review of how others use labels for internal organization (both in big and small open source projects). We are aware that many _trendy_ projects currently don't follow this kind of classification in labels, but those presented in this repo could fit as a basis for common management tasks and organizations. Also the convention-naming for labels depends on your project management setup: if you use milestones, GH projects, etc., you will need to adapt/select the labels' name to meet your workflow.

Some links:
  * https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63
  * https://github.com/dotnet/roslyn/wiki/Labels-used-for-issues
  * https://github.com/FakeItEasy/FakeItEasy/wiki/Issue-labels
  * https://docs.gitlab.com/ee/user/project/labels.html
  * https://www.quora.com/What-is-the-best-way-to-name-GitHub-issue-labels
  * https://github.com/Relequestual/sensible-github-labels
  * https://github.com/azu/github-label-setup

If you have anything to add to this discussion or proposals to improve these labels, we are open to continue the discussion 🙂

**Comment by abdonrd** [comment]
@lauriejim not public projects with the labels right now. 😕

**Comment by lauriejim** [comment]
With [Strapi](https://github.com/strapi/strapi) project we are using it since fews months and it works good.

And thank you for your links

**Comment by abdonrd** [comment]
@lauriejim yes! We get inspiration from several projects, including Strapi! :)
